version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - $PWD/data:/var/lib/mysql
      # - data:/var/lib/mysql 
      - $PWD/init:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
      
volumes:
  data:
    driver: local
